name: self_discipline_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter

    # state management
  flutter_riverpod:
    ^2.6.1

    # Local Database
  hive: ^2.2.3
  hive_flutter:
    ^1.1.0

    # Notification
  flutter_local_notifications: ^13.0.0

  google_fonts: ^6.2.1
  high_chart: ^2.1.0
  intl: ^0.18.1
  lottie: ^3.1.3
  auto_route: ^7.8.4

  device_preview: 1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^2.0.1
  very_good_analysis: ^5.1.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lotties/
    - assets/images/
    - assets/icons/
